---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pfe-app
  template:
    metadata:
      labels:
        app: pfe-app
    spec:
      containers:
      - name: pfe-container
        image: mousaab/pfe-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pfe-service
spec:
  type: NodePort
  selector:
    app: pfe-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
